#!/bin/sh

build() {
	add_systemd_unit cryptsetup-pre.target
	add_systemd_unit ykfde-2f.service
	add_symlink "/usr/lib/systemd/system/sysinit.target.wants/ykfde-2f.service" "../ykfde-2f.service"
	add_file /usr/lib/systemd/scripts/ykfde-2f
	add_binary keyctl
	add_binary systemd-ask-password
}

help() {
	echo "This hook adds 2nd factor support for Yubikey full disk encryption."
}
