#!/bin/sh

build() {
	# install files to initramfs
	add_binary /usr/lib/udev/ykfde
	add_file /usr/lib/initcpio/udev/20-ykfde.rules /usr/lib/udev/rules.d/20-ykfde.rules
	add_file /etc/ykfde.conf
}

help() {
	echo "This hook adds support for opening LUKS devices with Yubico key."
	echo "Please use command 'ykfde' to prepare."
	echo "The hook ykfde-cpio does NOT include challenges! Please load"
	echo "additional cpio archive with bootloader."
}
