#!/bin/sh

build() {
	add_binary ykchalresp
	add_binary tr
	add_binary /usr/lib/udev/ykfde
	add_binary /usr/lib/systemd/systemd-reply-password
	add_file /usr/lib/initcpio/udev/20-ykfde.rules /usr/lib/udev/rules.d/20-ykfde.rules
	add_file /etc/ykfde.conf
	add_file /etc/ykfde-challenge /
	add_module 'usbhid'
}

help() {
	echo "This hook adds support for opening LUKS devices with Yubico key."
	echo "Please use command 'ykfde' to prepare."
}
